data_path: "in_put/Wheat_protein.fasta"
output_folder: "./out_put"
step1_output_file: "Step_1.txt"
regular: ">(.*?)\\s"
protease: "LysargiNase"
missed_cleavages: 2
min_len: 2
max_len: 10

step2_output_file: "Step_2.txt"

step3_output_folder: "step3_results"

step4_output_folder: "step4_results"

step5_output_folder: "step5_results"


step6_output_folder: "step6_results"

step7_output_folder: "step7_results"

step8_output_folder: "step8_results"




step9_output_folder: "step9_results"
Prodigy_distance_cutoff: 5.5


